# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create(:username => "nicola", :email => "nicola.di.trani@accenture.com", :password => "nicola", :password_confirmation => "nicola")

s = Supplier.new(:name=>"Paninaro 2.0", :address=>"",:phone=>"",:email=>"alimentari_r_m@libero.it")
s.save

Product.create(:name=>"Panino Bolzano", :description => "Pane a scelta, speck, fontina, melanzane grigliate", :price => 2.20, :supplier => s)
Product.create(:name=>"Panino Trento", :description => "Pane a scelta, cotto, salsa funghi, zucchine grigliate", :price => 2.20, :supplier => s)
Product.create(:name=>"Panino Verona", :description => "Pane a scelta, soppresssa, gorgonzola, zucchine e melanzane grigliate", :price => 2.20, :supplier => s)



s = Supplier.new(:name=>"Pizza Scooter", :address=>"Via A.Manzoni, 7",:phone=>"045 8101152",:email=>"")
s.save


Product.create(:name=>"Insalata Jessy", :price => 5.5, :description => "ins. verde, cirio, mozzarella, olive greche, gamberetti", :supplier => s)
Product.create(:name=>"Insalata Franci", :price => 5.0, :description => "ins. verde, rucola, cirio, tonno, cipolla, capperi, origano", :supplier => s)
Product.create(:name=>"Insalata Nicole", :price => 5.5, :description => "ins. verde, mozzarella, mais, gamberetti", :supplier => s)
Product.create(:name=>"Insalata Camilla", :price => 5.0, :description => "ins. verde, radicchio rosso, olive greche, mozzarella", :supplier => s)
Product.create(:name=>"Bresaola, rucola, grana", :price => 6.0, :description => "bresaola, rucola, grana", :supplier => s)
Product.create(:name=>"Caprese", :price => 6.00, :description => "mozzarella, cirio, basilico, origano", :supplier => s)
Product.create(:name=>"Prosciutto & melone (in stagione)", :price => 6.00, :description => "prosciutto, melone", :supplier => s)
Product.create(:name=>"Bibite bottiglia 1,5 lt.", :price => 2.90, :supplier => s)
Product.create(:name=>"Bibite lattina 33 cl.", :price => 1.60, :supplier => s)
Product.create(:name=>"Birre lattina 33 cl.", :price => 1.60, :supplier => s)
Product.create(:name=>"Birre bottiglia 33 cl.", :price => 2.90, :supplier => s)
Product.create(:name=>"Birre bottiglia 66 cl.", :price => 3.30, :supplier => s)
Product.create(:name=>"Margherita", :description => "Pomodoro, mozzarella", :price => 3.50, :supplier => s)
Product.create(:name=>"Salsiccia e funghi ", :description => "Pomodoro, mozzarella, salsiccia, funghi", :price => 4.50, :supplier => s)
Product.create(:name=>"Panna e speck", :description => "Pomodoro, mozzarella, panna fresca, speck", :price => 5.50, :supplier => s)
Product.create(:name=>"Pizza Scooter", :price => 6.70, :description => "pomodoro, mozzarella, prosciutto, funghi, salamino piccante, carciofi, wurstel", :supplier => s)
Product.create(:name=>"Pizza Angelo", :price => 6.90, :description => "pomodoro, mozzarella, pate' di olive, gorgonzola dolce, speck", :supplier => s)
Product.create(:name=>"Pizza Porcini", :price => 6.90, :description => "pomodoro, mozzarella, porcini, grana", :supplier => s)
Product.create(:name=>"Pizza Pizzaiolo", :price => 6.90, :description => "pomodoro, mozzarella, pate' di olive, gorgonzola dolce, verdure miste", :supplier => s)
Product.create(:name=>"Pizza Gamberucola", :price => 6.90, :description => "pomodoro, mozzarella, gamberetti, rucola", :supplier => s)
Product.create(:name=>"Pizza Ortolana", :price => 6.60, :description => "pomodoro, mozzarella, 5 tipi di verdure, grana", :supplier => s)
Product.create(:name=>"Pizza Grigliata", :price => 6.60, :description => "pomodoro, mozzarella, melanzane, peperoni, zucchine, grana", :supplier => s)
Product.create(:name=>"Pizza Elena", :price => 6.90, :description => "pomodoro, mozzarella, mascarpone, rucola, prosciutto crudo", :supplier => s)
Product.create(:name=>"Pizza Mare e Monti", :price => 6.90, :description => "pomodoro, mozzarella, porcini, frutti di mare", :supplier => s)
Product.create(:name=>"Pizza Braccio di ferro", :price => 5.60, :description => "pomodoro, mozzarella, spinaci, ricotta, grana", :supplier => s)
Product.create(:name=>"Pizza Scoglio", :price => 7.60, :description => "pomodoro, mozzarella, frutti di mare, prezzemolo", :supplier => s)
Product.create(:name=>"Pizza Delizia", :price => 7.40, :description => "pomodoro, mozzarella, misto bosco, gorgonzola, salsiccia dolce, crudo", :supplier => s)
Product.create(:name=>"Pizza Estate", :price => 5.60, :description => "pomodoro, mozzarella, pomodorini cirio, rucola", :supplier => s)
Product.create(:name=>"Pizza Contadina", :price => 7.40, :description => "pomodoro, mozzarella, melanzane, scamorza, grana, speck", :supplier => s)
Product.create(:name=>"Pizza Boscaiola", :price => 7.10, :description => "pomodoro, mozzarella, porcini, speck", :supplier => s)
Product.create(:name=>"Pizza Mangia e bevi", :price => 5.80, :description => "pomodoro, mozzarella, salame piccante, capperi, acciughe, peperoni, peperoncino", :supplier => s)
Product.create(:name=>"Pizza Casa", :price => 7.00, :description => "pomodoro, mozzarella, prosciutto, funghi, patate carciofi, peperoni, salame piccante, grana", :supplier => s)
Product.create(:name=>"Pizza Misto bosco", :price => 6.90, :description => "pomodoro, mozzarella, misto bosco, grana", :supplier => s)
Product.create(:name=>"Pizza Nicolas", :price => 6.40, :description => "pomodoro, mozzarella, spinaci, zucchine, patate, tonno", :supplier => s)
Product.create(:name=>"Pizza 4 stagioni", :price => 6.10, :description => "pomodoro, mozzarella, prosciutto, funghi, carciofi", :supplier => s)
Product.create(:name=>"Pizza 4 formaggi", :price => 5.80, :description => "pomodoro, mozzarella, emmenthal, gorgonzola dolce, grana", :supplier => s)
Product.create(:name=>"Pizza Calzone 4 formaggi", :price => 5.80, :description => "pomodoro, mozzarella, emmenthal, gorgonzola dolce, grana", :supplier => s)
Product.create(:name=>"Pizza Calzone", :price => 5.60, :description => "pomodoro, mozzarella, prosciutto, funghi, ricotta", :supplier => s)
Product.create(:name=>"Pizza Rucola e Mascarpone", :price => 6.10, :description => "pomodoro, mozzarella, rucola, mascarpone", :supplier => s)
Product.create(:name=>"Pizza Affumicata", :price => 6.40, :description => "pomodoro, mozzarella, scamorza, speck", :supplier => s)
Product.create(:name=>"Pizza Gorgonzola e noci", :price => 5.60, :description => "pomodoro, mozzarella, gorgonzola dolce, noci", :supplier => s)
Product.create(:name=>"Pizza Crudo o Speck", :price => 5.90, :description => "pomodoro, mozzarella, crudo o speck", :supplier => s)
Product.create(:name=>"Pizza Porchy.s", :price => 6.40, :description => "pomodoro, mozzarella, prosciutto, wurstel, salame piccante e dolce,", :supplier => s)
Product.create(:name=>"Pizza pancetta affumicata, porchetta", :supplier => s)
Product.create(:name=>"Pizza Italia", :price => 5.60, :description => "pomodoro, mozzarella, pomodorini cirio, spinaci, ricotta", :supplier => s)
Product.create(:name=>"Pizza Delicata", :price => 6.40, :description => "pomodoro, mozzarella, philadelphia, scamorza, mascarpone, pomodorini", :supplier => s)
Product.create(:name=>"Pizza Superba", :price => 6.40, :description => "pomodoro, mozzarella, philadelphia, speck", :supplier => s)
Product.create(:name=>"Pizza Casereccia", :price => 6.90, :description => "pomodoro, mozzarella, bresaola, rucola", :supplier => s)
Product.create(:name=>"Pizza Gorgonzola e crudo", :price => 6.90, :description => "pomodoro, mozzarella, gorgonzola dolce, crudo", :supplier => s)
Product.create(:name=>"Pizza Sarda", :price => 6.10, :description => "pomodoro, mozzarella salsiccia dolce, pecorino, olive nere", :supplier => s)
Product.create(:name=>"Pizza Stracchino e rucola", :price => 6.10, :description => "pomodoro, mozzarella, stracchino e rucola", :supplier => s)
Product.create(:name=>"Pizza Salmone", :price => 6.90, :description => "pomodoro, mozzarella, salmone", :supplier => s)
Product.create(:name=>"Pizza Primavera", :price => 6.10, :description => "pomodoro, mozzarella, pomodorini, asparagi, grana", :supplier => s)
Product.create(:name=>"Pizza Autunno", :price => 6.40, :description => "pomodoro, mozzarella, funghi misti di bosco, salsiccia dolce", :supplier => s)
Product.create(:name=>"Pizza Inverno", :price => 6.60, :description => "pomodoro, mozzarella, radicchio rosso, pancetta affumicata, mascarpone", :supplier => s)
Product.create(:name=>"Pizza Foresta nera", :price => 7.60, :description => "pomodoro, mozzarella, porcini, tartufo, grana", :supplier => s)
Product.create(:name=>"Pizza Canadese", :price => 6.90, :description => "pomodoro, mozzarella, salsiccia dolce, funghi misti di bosco, emmenthal", :supplier => s)
Product.create(:name=>"Pizza Gustosa", :price => 6.10, :description => "pomodoro, mozzarella, gorgonzola dolce, salsiccia dolce, cipolla", :supplier => s)
Product.create(:name=>"Pizza Diavola", :price => 6.90, :description => "pomodoro, mozzarella, salamino piccante, peperoni, prosciutto", :supplier => s)
Product.create(:name=>"Pizza Francese", :price => 6.90, :description => "pomodoro, mozzarella, brie, speck", :supplier => s)
Product.create(:name=>"Pizza Camino", :price => 6.60, :description => "pomodoro, mozzarella, ricotta affumicata, speck", :supplier => s)
Product.create(:name=>"Pizza La Olfa", :price => 7.40, :description => "pomodoro, mozzarella, misto bosco, philadelphia, speck", :supplier => s)
Product.create(:name=>"Pizza Tony", :price => 7.10, :description => "pomodoro, mozzarella, melanzane, porcini, salsiccia dolce, grana", :supplier => s)
Product.create(:name=>"Pizza Saporita", :price => 6.90, :description => "pomodoro, mozzarella, carciofi, porchetta, scamorza", :supplier => s)
Product.create(:name=>"Pizza Marinara", :price => 3.90, :description => "pomodoro, olio, aglio e origano", :supplier => s)
